---
- name: Stop container before converting to template
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: pve
    vmid: "{{ k8s_template_id }}"
    state: stopped

- name: Convert container to template
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: pve
    vmid: "{{ k8s_template_id }}"
    state: template

- name: Create a full clone of the template container
  community.proxmox.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: pve
    vmid: "{{ item.container_id }}"
    clone: "{{ k8s_template_id }}"
    hostname: "{{ item.hostname }}"
    clone_type: linked
    state: present
  loop: "{{ k8s_clone_list }}"

- name: Set container IP
  community.proxmox.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: pve
    vmid: "{{ item.container_id }}"
    hostname: "{{ item.hostname }}"
    netif:
      net0: "name=eth0,bridge=vmbr0,ip={{ item.ipaddr }},gw={{ gateway_ipaddr }}"
    state: present
  loop: "{{ k8s_clone_list }}"

- name: Start the cloned containers
  community.general.proxmox:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: pve
    vmid: "{{ item.container_id }}"
    state: started
  loop: "{{ k8s_clone_list }}"

- name: Wait for containers to be ready asynchronously
  wait_for:
    host: "{{ item.ipaddr }}"
    port: 22
    delay: 10
    timeout: 300
  loop: "{{ k8s_clone_list }}"
  loop_control:
    label: "{{ item.hostname }}"
  async: 300
  poll: 0

