services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:"{{ prometheus_version }}"
    restart: always
    ports:
      - "{{ prometheus_port }}:9090"
    volumes:
      - /srv/docker/prometheus:/etc/prometheus
    environment:
      TZ: "Asia/Tokyo"
    command: "--config.file=/etc/prometheus/prometheus.yaml"

  grafana:
    container_name: grafana
    image: grafana/grafana:"{{ grafana_version }}
    restart: always
    ports:
      - "{{ grafana_port }}:3000"
    environment:
      TZ: "Asia/Tokyo"

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:"{{ alertmanager_version }}"
    restart: always
    ports:
      - "{{ alertmanager_port }}:9093"
    volumes:
      - /srv/docker/alertmanager:/etc/alertmanager
    environment:
      TZ: "Asia/Tokyo"
    command: "--config.file=/etc/alertmanager/config.yaml"
