---
- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Add containerd config
  file:
    path: /etc/containerd/config.toml
    state: touch

- name: Add containerd config
  ansible.builtin.command: >
    containerd config default | tee /etc/containerd/config.toml
    if grep -q "SystemdCgroup = true" "/etc/containerd/config.toml"; 
    then
      echo "Config found, skip rewriting..."
    else
      sed -i -e "s/SystemdCgroup \\= false/SystemdCgroup \\= true/g" /etc/containerd/config.toml
    fi

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted