---
- name: Create new container for kubernetes template
  community.proxmox.proxmox:
    vmid: 5000
    node: pve
    password: {{ container_password | default('password')}}
    hostname: k8s-template
    ostemplate: 'local:vztmpl/{{ os_template_name }}'
    timezone: Asia/Tokyo
    unprivileged: false
    cores: {{ cpu_cores | default('4') }}
    memory: {{ memory_size | default('8192') }}
    swap: {{ swap_size | default('0') }}
    disk_volume:
      storage: local
      size: {{ disk_size | default('30G') }}
    netif:
      net0: "name=eth0,gw={{ gateway_ipaddr }},ip={{ k8s_template_ipaddr }},bridge=vmbr0"
    nameserver: {{ nameserver_ipaddr }}
    searchdomain: {{ searchdomain }}
    pubkey: {{ pubkey }}
    features:
      - nesting=1
      - keyctl=1
      - fuse=1

- name: Apply additional LXC parameters
  ansible.builtin.command: >
    pct set 5000
    -lxc.apparmor.profile unconfined
    -lxc.cap.drop ""
    -lxc.cgroup2.devices.allow "a"
    -lxc.mount.auto "proc:rw sys:rw cgroup:rw"
    -lxc.mount.entry "/dev/kmsg dev/kmsg none bind,optional,create=file"
    -lxc.mount.entry "/sys/fs/cgroup sys/fs/cgroup none bind,rw,optional 0 0"
  delegate_to: pve

- name: Start container
  community.proxmox.proxmox:
    vmid: 5000
    node: pve
    state: started
    timeout: 120

- name: Wait for container to be ready
  ansible.builtin.wait_for:
    host: {{ k8s_template_ipaddr }}
    port: 22
    delay: 10
    timeout: 300

- name: Configure template container
  include: configure.yaml

- name: Install packages into template container
  include: install.yaml
