---
- name: Construction Servers
  hosts: pve
  vars_files:
    - env_vars.yaml
  roles:
    - { role: pve, tags: pve }
    - { role: k8s-template, tags: k8s-template }

- name: Configure kubernetes template container
  hosts: k8s-template
  gather_facts: false
  vars_files:
    - env_vars.yaml
  roles:
    - { role: k8s-install, tags: k8s-install }

- name: Duplicate containers
  hosts: pve
  vars_files:
    - env_vars.yaml
  roles:
    - { role: make-nodes, tags: make-nodes }

- name: Build cluster (control plane)
  hosts: master
  gather_facts: false
  vars_files:
    - env_vars.yaml
  roles:
    - { role: make-cluster-cp, tags: make-cluster-cp }