---
- name: Update APT cache and upgrade all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Ensure pip3 is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install proxmoxer via apt
  apt:
    name:
      - python3-proxmoxer
      - python3-requests
    state: present
    update_cache: yes

- name: Download proxmox appliance container template
  community.proxmox.proxmox_template:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    node: pve
    storage: local
    content_type: vztmpl
    template: "{{ os_template_name }}"
    timeout: 600

- name: Add necessary modules for Kubernetes
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - nf_conntrack
    - overlay

- name: Fix sysctl parameters for Kubernetes
  sysctl:
    state: present
    name: net.netfilter.nf_conntrack_max
    value: 524288
    sysctl_set: yes
    reload: yes

- include_tasks: nfs.yaml

