---
- name: Download proxmox appliance container template
  community.proxmox.proxmox_template:
    node: pve
    api_user: root@pam
    api_password: 1q2w3e
    api_host: pve
    storage: local
    content_type: vztmpl
    template: {{ os_template_name }}

- name: Apt update & Apt upgrade
  apt: update_cache=yes upgrade=yes

- name: Add necessary modules for Kubernetes
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    with_items:
      - nf_conntrack
      - overlay

- name: Fix sysctl parameters for Kubernetes
  sysctl:
    state: present
    name: net.netfilter.nf_conntrack_max
    value: 524288
    sysctl_set: yes
    reload: yes

- include: nfs.yaml

