- name: Install Flannel CNI
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: flannel_install

- name: Install Calico CNI
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
# command: kubectl apply -f  https://raw.githubusercontent.com/projectcalico/calico/v3.30.4/manifests/calico.yaml
  when: calico_install
