---
- name: Fix sysctl parameters for Kubernetes
  sysctl:
    state: present
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6